name: psw
description: A Protect Password && Secret application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  in_app_purchase: ^3.0.2
  get: ^4.1.4
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  image: ^3.1.3
  flutter_native_image: ^0.0.6+1
  image_gallery_saver: ^1.7.1
  #  photo_view: ^0.13.0
  video_compress: ^3.1.0
  path_provider: ^2.0.2
  url_launcher: ^6.1.0
  screenshot: ^1.2.3
  barcode_widget: ^2.0.1
  timelines: ^0.1.0
  share_plus: ^3.0.1
  flutter_markdown: ^0.6.6
  device_info_plus: ^3.1.0

  pointycastle: 2.0.1
  asn1lib: 0.8.1
  bs58: 1.0.1
  protobuf: ^2.0.0
  dio: ^4.0.1

  permission_handler: ^9.2.0
  fab_circular_menu: ^1.0.2
  intl: ^0.17.0
  badges: ^2.0.1
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.3
  mime: ^1.0.0
  file_picker: ^4.5.1
  open_file: ^3.2.1
  reorderables: 0.4.1
  flutter_slidable: ^0.6.0
  modal_bottom_sheet: ^2.0.0
  gesture_password_widget: ^1.0.6
  material_floating_search_bar: ^0.2.6
  implicitly_animated_reorderable_list: ^0.2.5

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
#
#  video_compress:
#    git:
#      url: https://github.com/jonataslaw/VideoCompress.git
#      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
